### ISSUE TITLE
Collect team member pictures and info for About Us

### ISSUE THREAD

**Issue by primalpop** [zotbins/zotbins.github.io#1]

**Comment by okyang** [comment]
@primalpop still need pictures from luyi gui

**Comment by primalpop** [comment]
I included Prof. Gui's pic. We need a picture from Anne Kreighoff.

**Comment by okyang** [comment]
The dimensions of her picture is not correct. 
![image](https://user-images.githubusercontent.com/33404602/62406578-01513600-b563-11e9-969e-ecbfef482ec2.png)
