### ISSUE TITLE
Fall 2020 Revamp Part 2 - Team Page

### ISSUE THREAD

**Issue by jessechong** [zotbins/zotbins.github.io#17]
Part 2 of the revamp. This is "team.html".

Here are the mock ups
![image](https://user-images.githubusercontent.com/44284982/97383618-4ad62100-188b-11eb-8a70-0a3e25afc141.png)
![image](https://user-images.githubusercontent.com/44284982/97383633-50cc0200-188b-11eb-9e8f-96495fb8e15e.png)

Details:
1. "What is ZOWA"?
I will have to find a longer version of our team description. It will be a longer version of what u have on the landing page.

2. "Who is ZOWA"?
You can follow the TIPPERS format, my mockup, or whatever you think is best.
I think 3 people per row is good. 

**There are 3 sections: "Members", "Mentors", and "Alumni".**

**--MEMBERS--**
Each member should have the following details:
a) Profile picture and name
b) Major (CS, CSE, etc)
c) Class (of '21, of '20, of '19, etc)
d) Role (Web and App dev/lead, embedded systems dev/lead, waste recognition dev/lead, team lead)
 
For members, choose one of the following ordering options:
Option A) Team leads first, alphabetical; Subgroup leads second, alphabetical; everyone else, alphabetical
Option B) Everyone in the whole team alphabetical

**--MENTORS--**
For mentors, just do Professor Sharad first, Professor Nalini second, Primal third (like we have now).
Each mentor should have the following details:
a) Profile picture and name
b) Credential (PHD, PHD student)
c) Department (ICS department)

**--ALUMNI--**
For alumni, choose one of the following ordering options:
Option A) Owen first, then Josh second, then everyone else in alphabetical
Option B) Every alumni in alphabetical

Each alumni should have the following details:
a) Profile picture and name
b) Major (CS, CSE, etc)
c) Class (of '21, of '20, of '19, etc)
d) Past role (Web and App dev/lead, embedded systems dev/lead, waste recognition dev/lead, team lead)
e) currently at (some company, grad school, etc).

References:
1. https://tippers.ics.uci.edu/team
![image](https://user-images.githubusercontent.com/44284982/97383599-3db93200-188b-11eb-930d-71e3f8f5c7fb.png)

**Comment by primalpop** [comment]
Hi Jesse, Palak, 

The mockup looks well done and captures everything we discussed.  Few minor suggestions: 1) Split members into team leads (Jesse, Grace, Marissa) and members (the rest) 2) Split mentors into mentors (Primal) and faculty Advisors (Sharad, Nalini) 3) For Owen and Josh in alumni list them as co-founders in the details line 4) (Optional) Keeping up with the spirit on our intro meeting, include a spirit trash item with every person (just like a spirit animal)

**Comment by jessechong** [comment]
I like the spirit animal idea. It would be nice to give our team more character :)

Another thing I liked from the TIPPERS website is how they put the entire team logo in the background-- super clever. I think we could try incorporating that too with like a 75% transparent ZotBin logo.

See the giant TIPPERS "T" in the background? Take a look here:
![image](https://user-images.githubusercontent.com/44284982/97695518-66932000-1a61-11eb-8cdc-68942e73bda6.png)
